2024-12-06 00:22:59,095 - ERROR - Ignoring exception in on_guild_join
Traceback (most recent call last):
  File "/home/eklem/projects/FarmSimSociety/bot/.venv/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/eklem/projects/FarmSimSociety/bot/cogs/general.py", line 35, in on_guild_join
    if UserRepository.get_user_by_discord_id(self.bot.db, member.id):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eklem/projects/FarmSimSociety/bot/.venv/lib/python3.12/site-packages/database/repository.py", line 17, in get_user_by_discord_id
    return session.query(User).filter(User.discord_id == discord_id).first()
           ^^^^^^^^^^^^^
AttributeError: 'Database' object has no attribute 'query'
