2024-12-06 00:22:21,347 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-12-06 00:22:21,349 - INFO - logging in using static token
2024-12-06 00:22:21,854 - INFO - Shard ID None has connected to Gateway (Session ID: 60f978cc8c044c543ee3f678a626bddf).
2024-12-06 00:22:23,872 - INFO - Logged in as TEST#2082 (ID: 1219655857315385436)
2024-12-06 00:22:23,905 - INFO - Loaded cogs.economy
2024-12-06 00:22:23,909 - INFO - Loaded cogs.general
2024-12-06 00:22:23,910 - INFO - Loaded cogs.websocket_handler
2024-12-06 00:22:23,914 - INFO - Loaded cogs.admin
2024-12-06 00:22:59,095 - ERROR - Ignoring exception in on_guild_join
Traceback (most recent call last):
  File "/home/eklem/projects/FarmSimSociety/bot/.venv/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/eklem/projects/FarmSimSociety/bot/cogs/general.py", line 35, in on_guild_join
    if UserRepository.get_user_by_discord_id(self.bot.db, member.id):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eklem/projects/FarmSimSociety/bot/.venv/lib/python3.12/site-packages/database/repository.py", line 17, in get_user_by_discord_id
    return session.query(User).filter(User.discord_id == discord_id).first()
           ^^^^^^^^^^^^^
AttributeError: 'Database' object has no attribute 'query'
2024-12-06 00:25:24,809 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-12-06 00:25:24,823 - INFO - logging in using static token
2024-12-06 00:25:25,379 - INFO - Shard ID None has connected to Gateway (Session ID: f94b2df0f1a28d83caa15973e8f1bfee).
2024-12-06 00:25:27,383 - INFO - Logged in as TEST#2082 (ID: 1219655857315385436)
2024-12-06 00:25:27,392 - INFO - Loaded cogs.economy
2024-12-06 00:25:27,396 - INFO - Loaded cogs.general
2024-12-06 00:25:27,397 - INFO - Loaded cogs.websocket_handler
2024-12-06 00:25:27,401 - INFO - Loaded cogs.admin
